---
title: "R & Python"
author: "José María Arrieta Reyes"
date: "25/2/2021"
output:
  pdf_document: default
  html_document: default
---

# Python & R Together


Python coding :


```{r echo=FALSE}
library(reticulate)
use_python("/Users/Usuario/Anaconda3/python3")
use_condaenv("/Users/Usuario/Anaconda3/envs/machinelearning")
os = import("os")
os$listdir(".")
```

```{r}
source_python("../script/add.py")
add(5,5)
```

```{r}
np = import("numpy",convert = FALSE)
x = np$array(c(1:4))
sum = x$cumsum()
print(sum)
py_to_r(sum)
```

```{r}
py_help(os$chdir)
#help(py_to_r)
```

## Arrays
```{r}
a = np_array(c(1:10), order="C")
a
```

```{r}
datos <- iris
head(datos)
data_py <- r_to_py(datos)
```


```{python}
import numpy as np
import pandas as pd

r.data_py.head()
```

## Sparse Matrix

```{r}
library(Matrix)
N <- 6
set.seed(2021)
sparse_mat <- sparseMatrix(
  i = sample(N,N,replace = F),
  j = sample(N,N,replace = F),
  x = runif(N),
  dims = c(N,N)
)
sparse_mat
sparse_mat_py <- r_to_py(sparse_mat)
```

```{python}
r.sparse_mat_py
```



